// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package db

import (
	"context"
	"database/sql"
)

const createMerchant = `-- name: CreateMerchant :execresult
INSERT INTO merchants (
    name,
    phone,
    commission_percentage
)
VALUES (
    ?,
    ?,
    ?
)
`

type CreateMerchantParams struct {
	Name                 string
	Phone                string
	CommissionPercentage string
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant, arg.Name, arg.Phone, arg.CommissionPercentage)
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT
    merchant_id,
    name,
    phone,
    commission_percentage
FROM merchants
WHERE merchant_id = ?
`

func (q *Queries) GetMerchantByID(ctx context.Context, merchantID int32) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, merchantID)
	var i Merchant
	err := row.Scan(
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.CommissionPercentage,
	)
	return i, err
}

const getMerchantByPhone = `-- name: GetMerchantByPhone :one
SELECT
    merchant_id,
    name,
    phone,
    commission_percentage
FROM merchants
WHERE phone = ?
`

func (q *Queries) GetMerchantByPhone(ctx context.Context, phone string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByPhone, phone)
	var i Merchant
	err := row.Scan(
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.CommissionPercentage,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT
    merchant_id,
    name,
    phone,
    commission_percentage
FROM merchants
ORDER BY merchant_id
`

func (q *Queries) ListMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.MerchantID,
			&i.Name,
			&i.Phone,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :execresult
UPDATE merchants
SET commission_percentage = ?
WHERE merchant_id = ?
`

type UpdateMerchantCommissionParams struct {
	CommissionPercentage string
	MerchantID           int32
}

func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMerchantCommission, arg.CommissionPercentage, arg.MerchantID)
}
