// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    name,
    email
)
VALUES (
    ?,
    ?
)
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
WHERE user_id = ?
FOR UPDATE
`

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDForUpdate, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
ORDER BY user_id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDue = `-- name: UpdateUserDue :execresult
UPDATE users
SET current_due = ?
WHERE user_id = ?
`

type UpdateUserDueParams struct {
	CurrentDue string
	UserID     int32
}

func (q *Queries) UpdateUserDue(ctx context.Context, arg UpdateUserDueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserDue, arg.CurrentDue, arg.UserID)
}
